/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as CardRouteImport } from './routes/card'

const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/card': typeof CardRoute
  '/counter': typeof CounterRoute
}
export interface FileRoutesByTo {
  '/card': typeof CardRoute
  '/counter': typeof CounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/card': typeof CardRoute
  '/counter': typeof CounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/card' | '/counter'
  fileRoutesByTo: FileRoutesByTo
  to: '/card' | '/counter'
  id: '__root__' | '/card' | '/counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CardRoute: typeof CardRoute
  CounterRoute: typeof CounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CardRoute: CardRoute,
  CounterRoute: CounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
